export interface FilterPreset {
  id: string;
  name: string;
  icon: string;
  description: string;
  blur: number;
  brightness: number;
  contrast: number;
  saturate: number;
  hueRotate: number;
  tintColor: string;
  tintOpacity: number;
  vignetteStrength: number;
  isFree: boolean;
  /** Optional radial gradient overlay for magical effects */
  radialGlow?: { color: string; size: number; opacity: number };
  /** Optional edge glow effect */
  edgeGlow?: { color: string; strength: number };
}

export const FILTER_PRESETS: FilterPreset[] = [
  {
    id: "none",
    name: "None",
    icon: "◇",
    description: "No filter",
    blur: 0,
    brightness: 1.0,
    contrast: 1.0,
    saturate: 1.0,
    hueRotate: 0,
    tintColor: "transparent",
    tintOpacity: 0,
    vignetteStrength: 0,
    isFree: true,
  },
  {
    id: "cosmic-dream",
    name: "Cosmic",
    icon: "◈",
    description: "Deep purple nebula",
    blur: 1.5,
    brightness: 1.3,
    contrast: 1.5,
    saturate: 2.2,
    hueRotate: -25,
    tintColor: "rgba(120, 30, 220, 0.5)",
    tintOpacity: 0.5,
    vignetteStrength: 0.8,
    isFree: true,
    radialGlow: { color: "rgba(120, 30, 220, 0.15)", size: 0.6, opacity: 0.4 },
  },
  {
    id: "nebula-glow",
    name: "Nebula",
    icon: "⟡",
    description: "Intense pink haze",
    blur: 2,
    brightness: 1.4,
    contrast: 1.2,
    saturate: 2.0,
    hueRotate: 20,
    tintColor: "rgba(255, 60, 180, 0.45)",
    tintOpacity: 0.45,
    vignetteStrength: 0.7,
    isFree: true,
    radialGlow: { color: "rgba(255, 60, 180, 0.12)", size: 0.5, opacity: 0.5 },
  },
  {
    id: "golden-hour",
    name: "Solar",
    icon: "✧",
    description: "Warm amber glow",
    blur: 0.8,
    brightness: 1.5,
    contrast: 1.4,
    saturate: 2.5,
    hueRotate: -12,
    tintColor: "rgba(255, 150, 20, 0.4)",
    tintOpacity: 0.4,
    vignetteStrength: 0.6,
    isFree: true,
    radialGlow: { color: "rgba(255, 180, 50, 0.1)", size: 0.7, opacity: 0.3 },
  },
  {
    id: "starlight",
    name: "Stellar",
    icon: "⬡",
    description: "Cool icy blue",
    blur: 1,
    brightness: 1.2,
    contrast: 1.7,
    saturate: 0.5,
    hueRotate: 40,
    tintColor: "rgba(40, 120, 255, 0.45)",
    tintOpacity: 0.45,
    vignetteStrength: 0.7,
    isFree: true,
    radialGlow: { color: "rgba(40, 120, 255, 0.1)", size: 0.5, opacity: 0.4 },
  },
  {
    id: "aurora",
    name: "Aurora",
    icon: "◎",
    description: "Green-pink shift",
    blur: 1.5,
    brightness: 1.3,
    contrast: 1.4,
    saturate: 2.0,
    hueRotate: 80,
    tintColor: "rgba(30, 220, 160, 0.4)",
    tintOpacity: 0.4,
    vignetteStrength: 0.6,
    isFree: true,
    radialGlow: { color: "rgba(30, 220, 160, 0.1)", size: 0.6, opacity: 0.35 },
  },
  {
    id: "void",
    name: "Void",
    icon: "⊗",
    description: "Dark moody crush",
    blur: 0,
    brightness: 0.4,
    contrast: 2.5,
    saturate: 0.2,
    hueRotate: 0,
    tintColor: "rgba(5, 0, 20, 0.6)",
    tintOpacity: 0.6,
    vignetteStrength: 0.95,
    isFree: true,
  },
  {
    id: "ethereal",
    name: "Ethereal",
    icon: "◇",
    description: "Dreamy soft blur",
    blur: 4,
    brightness: 1.6,
    contrast: 0.6,
    saturate: 1.6,
    hueRotate: -15,
    tintColor: "rgba(255, 170, 150, 0.35)",
    tintOpacity: 0.35,
    vignetteStrength: 0.5,
    isFree: true,
    radialGlow: { color: "rgba(255, 200, 180, 0.1)", size: 0.8, opacity: 0.3 },
  },
  {
    id: "inferno",
    name: "Ignis",
    icon: "△",
    description: "Fiery red-orange",
    blur: 0.8,
    brightness: 1.3,
    contrast: 1.8,
    saturate: 3.0,
    hueRotate: -40,
    tintColor: "rgba(255, 50, 0, 0.45)",
    tintOpacity: 0.45,
    vignetteStrength: 0.8,
    isFree: true,
    radialGlow: { color: "rgba(255, 80, 20, 0.12)", size: 0.5, opacity: 0.4 },
  },
  {
    id: "frost",
    name: "Cryo",
    icon: "▽",
    description: "Frozen desaturated",
    blur: 0.5,
    brightness: 1.5,
    contrast: 1.2,
    saturate: 0.1,
    hueRotate: 15,
    tintColor: "rgba(160, 210, 255, 0.4)",
    tintOpacity: 0.4,
    vignetteStrength: 0.6,
    isFree: true,
    radialGlow: { color: "rgba(160, 210, 255, 0.08)", size: 0.6, opacity: 0.3 },
  },
  {
    id: "noir",
    name: "Noir",
    icon: "◉",
    description: "Black and white",
    blur: 0,
    brightness: 1.0,
    contrast: 2.0,
    saturate: 0,
    hueRotate: 0,
    tintColor: "rgba(0, 0, 0, 0.2)",
    tintOpacity: 0.2,
    vignetteStrength: 0.9,
    isFree: true,
  },
  {
    id: "retro",
    name: "Analog",
    icon: "▣",
    description: "Vintage film look",
    blur: 0.5,
    brightness: 1.2,
    contrast: 1.5,
    saturate: 0.6,
    hueRotate: -20,
    tintColor: "rgba(200, 150, 60, 0.35)",
    tintOpacity: 0.35,
    vignetteStrength: 0.7,
    isFree: true,
  },
  {
    id: "neon",
    name: "Neon",
    icon: "◆",
    description: "Electric neon glow",
    blur: 0.8,
    brightness: 1.4,
    contrast: 1.7,
    saturate: 2.8,
    hueRotate: -30,
    tintColor: "rgba(180, 40, 255, 0.45)",
    tintOpacity: 0.45,
    vignetteStrength: 0.7,
    isFree: true,
    radialGlow: { color: "rgba(180, 40, 255, 0.12)", size: 0.4, opacity: 0.5 },
    edgeGlow: { color: "rgba(180, 40, 255, 0.3)", strength: 0.4 },
  },
  {
    id: "sunset",
    name: "Dusk",
    icon: "◐",
    description: "Warm orange-pink",
    blur: 0.8,
    brightness: 1.3,
    contrast: 1.4,
    saturate: 2.2,
    hueRotate: -8,
    tintColor: "rgba(255, 100, 50, 0.4)",
    tintOpacity: 0.4,
    vignetteStrength: 0.6,
    isFree: true,
    radialGlow: { color: "rgba(255, 100, 50, 0.1)", size: 0.6, opacity: 0.35 },
  },
  {
    id: "ocean",
    name: "Abyss",
    icon: "◉",
    description: "Deep teal-blue",
    blur: 1,
    brightness: 1.1,
    contrast: 1.5,
    saturate: 1.8,
    hueRotate: 50,
    tintColor: "rgba(0, 130, 180, 0.4)",
    tintOpacity: 0.4,
    vignetteStrength: 0.7,
    isFree: true,
    radialGlow: { color: "rgba(0, 130, 180, 0.1)", size: 0.5, opacity: 0.4 },
  },
  {
    id: "dreamscape",
    name: "Dream",
    icon: "⟡",
    description: "Soft lavender dream",
    blur: 2.5,
    brightness: 1.5,
    contrast: 0.8,
    saturate: 1.8,
    hueRotate: -30,
    tintColor: "rgba(180, 120, 255, 0.4)",
    tintOpacity: 0.4,
    vignetteStrength: 0.5,
    isFree: true,
    radialGlow: { color: "rgba(180, 120, 255, 0.12)", size: 0.7, opacity: 0.4 },
  },
  {
    id: "rose-gold",
    name: "Flora",
    icon: "✧",
    description: "Warm rosy glow",
    blur: 0.5,
    brightness: 1.3,
    contrast: 1.3,
    saturate: 1.6,
    hueRotate: -5,
    tintColor: "rgba(255, 150, 180, 0.35)",
    tintOpacity: 0.35,
    vignetteStrength: 0.5,
    isFree: true,
    radialGlow: { color: "rgba(255, 150, 180, 0.1)", size: 0.6, opacity: 0.35 },
  },
  {
    id: "supernova",
    name: "Supernova",
    icon: "✧",
    description: "Explosive cosmic burst",
    blur: 0.3,
    brightness: 1.6,
    contrast: 1.8,
    saturate: 2.5,
    hueRotate: -15,
    tintColor: "rgba(255, 200, 50, 0.3)",
    tintOpacity: 0.3,
    vignetteStrength: 0.4,
    isFree: false,
    radialGlow: { color: "rgba(255, 200, 50, 0.2)", size: 0.9, opacity: 0.6 },
    edgeGlow: { color: "rgba(255, 150, 50, 0.4)", strength: 0.5 },
  },
  {
    id: "black-hole",
    name: "Black Hole",
    icon: "⊗",
    description: "Extreme dark center pull",
    blur: 0,
    brightness: 0.3,
    contrast: 3.0,
    saturate: 0.1,
    hueRotate: 0,
    tintColor: "rgba(0, 0, 10, 0.7)",
    tintOpacity: 0.7,
    vignetteStrength: 0.98,
    isFree: false,
    radialGlow: { color: "rgba(100, 50, 200, 0.15)", size: 0.3, opacity: 0.8 },
  },
  {
    id: "crystal",
    name: "Crystal",
    icon: "◆",
    description: "Prismatic light split",
    blur: 0.3,
    brightness: 1.4,
    contrast: 1.6,
    saturate: 2.0,
    hueRotate: 25,
    tintColor: "rgba(200, 180, 255, 0.3)",
    tintOpacity: 0.3,
    vignetteStrength: 0.5,
    isFree: false,
    edgeGlow: { color: "rgba(200, 180, 255, 0.5)", strength: 0.6 },
  },
  {
    id: "plasma",
    name: "Plasma",
    icon: "◎",
    description: "Electric energy field",
    blur: 0.5,
    brightness: 1.3,
    contrast: 1.9,
    saturate: 2.6,
    hueRotate: 50,
    tintColor: "rgba(100, 200, 255, 0.35)",
    tintOpacity: 0.35,
    vignetteStrength: 0.7,
    isFree: false,
    radialGlow: { color: "rgba(100, 200, 255, 0.15)", size: 0.5, opacity: 0.5 },
    edgeGlow: { color: "rgba(100, 200, 255, 0.4)", strength: 0.5 },
  },
];

export const FRAME_OPTIONS = [
  { id: "none", name: "None", icon: "◇" },
  { id: "galaxy-border", name: "Vortex", icon: "◎" },
  { id: "constellation-ring", name: "Stellar", icon: "✧" },
  { id: "nebula-corners", name: "Nebula", icon: "◈" },
  { id: "star-field", name: "Prism", icon: "△" },
  { id: "cosmic-halo", name: "Halo", icon: "⬡" },
  { id: "void-edge", name: "Abyss", icon: "⊗" },
  { id: "aurora-ribbon", name: "Aurora", icon: "◎" },
  { id: "crystal-border", name: "Crystal", icon: "◆" },
  { id: "moon-phase", name: "Luna", icon: "◐" },
  { id: "solar-flare", name: "Solar", icon: "▽" },
  { id: "minimal-glow", name: "Glow", icon: "◇" },
];

export function getFilterCSS(filter: FilterPreset): string {
  return `blur(${filter.blur}px) brightness(${filter.brightness}) contrast(${filter.contrast}) saturate(${filter.saturate}) hue-rotate(${filter.hueRotate}deg)`;
}
