export const PROMPTS: string[] = [
  "What does silence sound like?",
  "Write about a color without naming it",
  "A letter you'll never send",
  "The space between heartbeats",
  "What the moon whispered",
  "The last thing you let go of",
  "A door you're afraid to open",
  "The sound of home",
  "What grows in the dark",
  "A conversation with your shadow",
  "The weight of a word unspoken",
  "Where do old seasons go?",
  "The smell before rain",
  "A window you keep returning to",
  "What the tide takes with it",
  "The first light after long darkness",
  "A song only you remember",
  "The shape of missing someone",
  "What the trees know",
  "A dream you can't finish",
  "The color of loneliness",
  "What lives beneath the surface",
  "A promise the wind made",
  "The silence after goodbye",
  "What your hands remember",
  "A map to a place that doesn't exist",
  "The hour between night and morning",
  "What the mirror doesn't show",
  "A garden planted in secret",
  "The sound of letting go",
  "What falls when no one watches",
  "A room you left but never left you",
  "The last page of a book",
  "What the fog hides",
  "A name you almost said",
  "The warmth of something broken",
  "What the river carries downstream",
  "A star that knows your name",
  "The distance between two people standing close",
  "What winter teaches patience",
  "A letter written by the rain",
  "The color of a forgotten afternoon",
  "What sleeps inside a stone",
  "A door that only opens inward",
  "The sound of snow falling",
  "What the earth remembers",
  "A bridge between two versions of you",
  "The taste of a word on your tongue",
  "What the old photographs don't say",
  "A shadow that refuses to leave",
  "The moment before the first breath",
  "What the candle knows about burning",
  "A forest you built inside yourself",
  "The echo of a room after everyone leaves",
  "What the wind carries from far away",
  "A question your heart keeps asking",
  "The color of the hour just before dawn",
  "What the spider weaves between worlds",
  "A song that has no words",
  "The weight of a held hand",
  "What the ocean says to the shore",
  "A wish you made on something ordinary",
  "The silence inside a snowfall",
  "What your childhood bedroom remembers",
  "A door left slightly open",
  "The smell of a place you've never been",
  "What the moon pulls from the deep",
  "A letter from your future self",
  "The sound a heart makes when it's full",
  "What grows between the cracks",
  "A train you didn't take",
  "The last color of autumn",
  "What the owl asks the dark",
  "A word that tastes like home",
  "The distance light travels to find you",
  "What the mirror sees when you leave",
  "A garden where grief grows into something beautiful",
  "The sound of an old house settling",
  "What the mountain holds in its silence",
  "A conversation held only in glances",
  "The shape of a prayer without words",
  "What stays after the fire goes out",
  "A book that changed the color of your thoughts",
  "The hour when the world is yours alone",
  "What the ant carries on its back",
  "A field you walked through in a dream",
  "The sound of absence",
  "What the river says to the stone it smooths",
  "A window facing the sea you've never seen",
  "The weight of a secret kept kindly",
  "What the lighthouse says to the lost",
  "A song your grandmother hummed",
  "The color of the air before a storm",
  "What hides inside a teacup",
  "A path that appears only at dusk",
  "The last thing winter says before it leaves",
  "What the spider knows about patience",
  "A door that opens to the sky",
  "The sound of roots breaking stone",
  "What the rain says to the roof",
  "A childhood game you still play alone",
  "The smell of the first day of spring",
  "What the moth loves about the flame",
  "A voice you hear in running water",
  "The shape of time passing",
  "What the salt says to the wound",
  "A dream you shared with someone and never spoke of",
  "The color of the moment you knew",
  "What the bone remembers about the body",
  "A garden tended by the dead",
  "The silence that lives inside a bell",
  "What the compass points to when you're lost",
  "A letter written in the margins",
  "The hour the fox comes to the garden",
  "What the river forgets about the mountain",
  "A song that changes meaning each year",
  "The weight of sunlight through a window",
  "What the tide says to the moon",
  "A map drawn from memory",
  "The sound a house makes when it's empty",
  "What the seed knows about the dark",
  "A question you ask the wind",
  "The color of a name you can't say",
  "What the lighthouse keeps in its heart",
  "A bridge built from longing",
  "The smell of the last page you read",
  "What the earth says to the buried",
  "A shadow that is taller than you",
  "The sound of closing a chapter",
  "What the rain remembers about the cloud",
  "A window you look through but never open",
  "The shape of what you've outgrown",
  "What the candle says to the dark room",
  "A dream you planted in someone else",
  "The color of the pause before an answer",
  "What the stone says to the moss that covers it",
  "A conversation you had with the ocean",
  "The weight of a coat you've taken off",
  "What the bird says to the empty nest",
  "A song that lives in your body",
  "The silence between two people who know each other",
  "What the river says to the fallen leaf",
  "A door that only opens on Tuesdays",
  "The sound of snow melting",
  "What the old woman remembers about the girl she was",
  "A garden where words grow into flowers",
  "The last hour of a perfect day",
  "What the tide takes and gives back different",
  "A map of all the places you've cried",
  "The color of the sky five minutes after sunset",
  "What the moth knows about the dark",
  "A letter you wrote to the wind",
  "The sound of a page turning",
  "What the root says to the tree",
  "A room that holds your childhood",
  "The weight of the first snow",
  "What the moon says to the sea it pulls",
  "A word that means everything and nothing",
  "The silence you carry like a stone",
  "What the river says to the valley it made",
  "A door that won't stay shut",
  "The sound of a name you love",
  "What the garden says to the abandoned house",
  "A letter to the person you were yesterday",
  "The shape of a question you're afraid to answer",
  "What the mountain says to the climber",
  "A song that plays only in your head",
  "The color of the moment before tears",
  "What the rain says to the seed",
  "A window that opens to a different world",
  "The weight of an apology not yet given",
  "What the lighthouse says to itself at night",
  "A dream that visits every winter",
  "The sound of a bridge being crossed",
  "What the bone says to the marrow",
  "A garden planted with old letters",
  "The hour when the city sleeps",
  "What the tide says to the cliff it shapes",
  "A voice that lives in the rustling of leaves",
  "The color of a memory you can't place",
  "What the spider says to the web it weaves",
  "A path that ends where it begins",
  "The weight of holding something you must let go",
  "What the river says to the boat that crosses it",
  "A door that opens only for the brave",
  "The sound of your name in someone else's mouth",
  "What the snow says to the footstep",
  "A letter you found in a book you didn't buy",
  "The shape of what you wish you'd said",
  "What the candle says to the moth",
  "A garden where silence grows",
  "The last color of the day",
  "What the mountain says to the valley below",
  "A song that sounds like rain on glass",
  "The weight of the first time you said no",
  "What the tide says to the sandcastle",
  "A window that looks out on yesterday",
  "The sound of a secret being kept",
  "What the seed says to the stone it pushes through",
  "A dream you carry like a key",
  "The color of the space between words",
  "What the river says to the bridge that crosses it",
  "A letter written by the wind to the trees",
  "The hour when the light turns gold",
  "What the moon says to the tide pool",
  "A door that leads to a question",
  "The sound of a flower opening",
  "What the root says to the earth that holds it",
  "A room where time moves differently",
  "The weight of a truth you've just discovered",
  "What the lighthouse says to the fog",
  "A song your body sings without you knowing",
  "The silence after a bell stops ringing",
  "What the rain says to the window",
  "A garden where the lost things grow",
  "The shape of the space between two stars",
  "What the stone says to the river that smooths it",
  "A letter you'll write tomorrow",
  "The color of the air inside a closed book",
  "What the owl says to the sleeping world",
  "A path made of footprints that aren't yours",
  "The weight of the day you stopped waiting",
  "What the tide says to the harbor",
  "A door that opens to your childhood",
  "The sound of a thought arriving",
  "What the mountain says to the cloud that rests on it",
  "A dream that tastes like salt",
  "The hour when the birds first sing",
  "What the spider says to the corner of the room",
  "A letter to the version of you who almost gave up",
  "The color of the moment you decided to stay",
  "What the river says to the waterfall it becomes",
  "A garden planted with what you've forgiven",
  "The weight of carrying someone else's story",
  "What the moon says to the wolf",
  "A window that frames a different sky each day",
  "The sound of memory arriving",
  "What the root says to the stone it breaks",
  "A door you keep in your pocket",
  "The silence inside a held breath",
  "What the tide says to the rock pool",
  "A song that lives between two people",
  "The shape of what you're becoming",
  "What the lighthouse says to the dawn",
  "A letter written in the language of trees",
  "The color of the space between sleeping and waking",
  "What the rain says to the leaf it falls on",
  "A garden where the rain is the gardener",
  "The weight of the last time you looked up",
  "What the river says to the fish that swim it",
  "A door that only opens in the rain",
  "The sound of a year ending",
  "What the stone says to the path it makes",
  "A room you visit only in dreams",
  "The hour when the moon is a sliver",
  "What the tide says to the lighthouse",
  "A letter to the silence that holds you",
  "The color of the moment before forgiveness",
  "What the mountain says to the eagle",
  "A garden where time grows backwards",
  "The weight of a wish spoken aloud",
  "What the rain says to the puddle it makes",
  "A door that opens to the past but you only look",
  "The sound of something ending softly",
  "What the root says to the rain that feeds it",
  "A dream that smells of woodsmoke",
  "The shape of what you cannot say",
  "What the moon says to the field it lights",
  "A letter to the child you were",
  "The color of the moment you knew it was love",
  "What the tide says to the shell it carries",
  "A garden where the old poems grow",
  "The weight of the first day you felt free",
  "What the river says to the marsh it widens into",
  "A door that opens when you stop knocking",
  "The sound of a word you just learned",
  "What the stone says to the lichen that adorns it",
  "A room filled with the sound of your own breathing",
  "The hour when the fox sleeps",
  "What the moon says to the snow",
  "A song that has no beginning",
  "The color of the silence between two storms",
  "What the rain says to the desert",
  "A garden planted with words you never spoke",
  "The weight of the morning you woke up different",
  "What the river says to the glacier it comes from",
  "A door that opens only on your birthday",
  "The sound of a candle being blown out",
  "What the root says to the worm",
  "A dream that ends with your name called",
  "The shape of what you've been given",
  "What the moon says to the window it enters",
  "A letter to the place you left",
  "The color of the air after you laugh",
  "What the tide says to the cliff it kisses",
  "A garden where sorrow blooms into wisdom",
  "The weight of the day you stopped running",
  "What the river says to the city it passes",
  "A door that opens to someone waiting",
  "The sound of distance being closed",
  "What the stone says to the fire that cracked it",
  "A room that smells of someone you miss",
  "The hour when the light is blue",
  "What the moon says to the tide it calls",
  "A song that means more each time you hear it",
  "The color of the moment before you speak",
  "What the rain says to the dust it settles",
  "A garden where patience grows wild",
  "The weight of the last lie you told",
  "What the river says to the bank it shapes",
  "A door that opens to a field of snow",
  "The sound of a word you've been carrying",
  "What the root says to the darkness it trusts",
  "A dream that smells of the sea",
  "The shape of what you've survived",
  "What the moon says to the child who points at it",
  "A letter to the fear that held you back",
  "The color of the space between breaths",
  "What the tide says to the night",
  "A garden planted with what you hope for",
  "The weight of the hand you chose to hold",
  "What the river says to the delta it creates",
  "A door that opens only in spring",
  "The sound of a year beginning",
  "What the stone says to the mountain it was part of",
  "A room where you keep your questions",
  "The hour when the owls call",
  "What the moon says to the pond it reflects in",
  "A song that has no end",
  "The color of the moment you let go",
  "What the rain says to the roof it drums on",
  "A garden where what you planted by accident grew tallest",
  "The weight of the story you tell yourself",
  "What the river says to the canyon it carved",
  "A door that opens to the person you're becoming",
  "The sound of something beginning quietly",
  "What the root says to the tree it feeds",
  "A dream that leaves a taste of honey",
  "The shape of what you've learned",
  "What the moon says to the wolf that howls",
  "A letter to the morning after the storm",
  "The color of the air in the room where you were born",
  "What the tide says to the moon that moves it",
  "A garden where grief becomes a tree",
  "The weight of the day you stopped explaining yourself",
  "What the river says to the sky it mirrors",
  "A door that opens to the view from your window",
  "The sound of the moment you understood",
  "What the stone says to the path beneath your feet",
  "A room filled with all the light you've ever seen",
  "The hour when the world is still",
  "What the moon says to itself",
  "A song that brings the rain",
  "The color of the silence after the question",
  "What the rain says to the sea it returns to",
  "A garden where every flower is a different goodbye",
  "The weight of the truth you haven't spoken yet",
  "What the river says to the rain that feeds it",
   "A door that opens when you say your own name",
   "The sound of the last page turning",
   "What the light says to the shadow it creates",
   "A garden where your tears water something new",
   "The weight of the breath before you speak",
   "What the stars say to the darkness between them",
   "A room you enter only when you're ready",
];

export function getDailyPrompt(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = now.getMonth() + 1;
  const date = now.getDate();
  const index = (year * 366 + month * 31 + date) % 365;
  return PROMPTS[index];
}
