import { TarotCard } from "./types";

export const MAJOR_ARCANA: TarotCard[] = [
  {
    id: "the-fool",
    name: "The Fool",
    number: 0,
    arcana: "major",
    uprightMeaning: "New beginnings, innocence, spontaneity, a free spirit. The Fool represents the start of a journey with unlimited potential.",
    reversedMeaning: "Recklessness, risk-taking, holding back, foolishness. A warning against naivety or poorly considered decisions.",
    keywords: ["beginnings", "innocence", "freedom", "spontaneity", "leap of faith"],
    symbolism: "The cliff edge represents the unknown. The white rose symbolizes purity. The small bag carries only essentials — wisdom travels light.",
    love: "A fresh start in love. Open your heart to new possibilities. If single, someone unexpected may appear.",
    career: "A new opportunity awaits. Take the leap, but read the fine print first.",
    personalGrowth: "Embrace the unknown. Growth requires leaving your comfort zone.",
    reflectionQuestion: "What new beginning am I being called toward?",
    element: "Air",
    astrologicalSign: "Uranus",
  },
  {
    id: "the-magician",
    name: "The Magician",
    number: 1,
    arcana: "major",
    uprightMeaning: "Manifestation, resourcefulness, power, inspired action. You have everything you need to succeed.",
    reversedMeaning: "Manipulation, poor planning, untapped talents. Skills exist but are being misused or ignored.",
    keywords: ["manifestation", "power", "skill", "willpower", "creation"],
    symbolism: "The four suits on the table represent all elements at hand. The infinity symbol above suggests unlimited potential.",
    love: "You have the power to create the relationship you desire. Be intentional about what you want.",
    career: "Your skills are noticed. Take initiative and make things happen.",
    personalGrowth: "You already possess what you need. Trust your abilities.",
    reflectionQuestion: "What am I ready to manifest in my life?",
    element: "Air",
    astrologicalSign: "Mercury",
  },
  {
    id: "the-high-priestess",
    name: "The High Priestess",
    number: 2,
    arcana: "major",
    uprightMeaning: "Intuition, sacred knowledge, the subconscious mind. Trust your inner voice and listen to your instincts.",
    reversedMeaning: "Secrets, disconnected from intuition, withdrawal. Something is being hidden — perhaps from yourself.",
    keywords: ["intuition", "mystery", "inner voice", "wisdom", "patience"],
    symbolism: "The veil between the pillars hides sacred knowledge. The moon at her feet represents the subconscious.",
    love: "Listen to your feelings. Not everything needs to be spoken aloud right now.",
    career: "The answer you seek will come through quiet reflection, not force.",
    personalGrowth: "Honor your intuition. The answers are within you.",
    reflectionQuestion: "What is my intuition trying to tell me?",
    element: "Water",
    astrologicalSign: "Moon",
  },
  {
    id: "the-empress",
    name: "The Empress",
    number: 3,
    arcana: "major",
    uprightMeaning: "Femininity, beauty, nature, nurturing, abundance. A time of growth, creativity, and sensual pleasure.",
    reversedMeaning: "Creative block, dependence, emptiness. Neglecting self-care or creative expression.",
    keywords: ["abundance", "nurturing", "fertility", "beauty", "nature"],
    symbolism: "The lush garden represents abundance. The Venus symbol on her shield connects to love and beauty.",
    love: "A deeply nurturing connection. Love is growing and flourishing.",
    career: "Creative projects flourish. Nurture your ideas — they will bear fruit.",
    personalGrowth: "Reconnect with your body and the natural world. Care for yourself.",
    reflectionQuestion: "Where in my life is abundance trying to grow?",
    element: "Earth",
    astrologicalSign: "Venus",
  },
  {
    id: "the-emperor",
    name: "The Emperor",
    number: 4,
    arcana: "major",
    uprightMeaning: "Authority, structure, control, stability. Establish order and take command of your situation.",
    reversedMeaning: "Tyranny, rigidity, excessive control. Too much structure can become a prison.",
    keywords: ["authority", "structure", "stability", "leadership", "discipline"],
    symbolism: "The throne of stone represents unshakeable foundation. The ram heads connect to Aries and pioneering energy.",
    love: "Stability and commitment. A protective, grounded partnership.",
    career: "Take charge. Leadership and organization bring results.",
    personalGrowth: "Build structure in your life. Discipline creates freedom.",
    reflectionQuestion: "Where do I need to take more responsibility?",
    element: "Fire",
    astrologicalSign: "Aries",
  },
  {
    id: "the-hierophant",
    name: "The Hierophant",
    number: 5,
    arcana: "major",
    uprightMeaning: "Spiritual wisdom, tradition, conformity, education. Seek guidance from established knowledge or a mentor.",
    reversedMeaning: "Personal beliefs, freedom, challenging the status quo. Finding your own spiritual path.",
    keywords: ["tradition", "teaching", "wisdom", "conformity", "guidance"],
    symbolism: "The crossed keys represent the conscious and subconscious. The pillars suggest structured knowledge.",
    love: "A traditional relationship or seeking relationship advice from someone wise.",
    career: "Follow established paths. Mentorship or formal education serves you now.",
    personalGrowth: "Learn from those who came before you, then make the wisdom your own.",
    reflectionQuestion: "What tradition or teaching resonates with me right now?",
    element: "Earth",
    astrologicalSign: "Taurus",
  },
  {
    id: "the-lovers",
    name: "The Lovers",
    number: 6,
    arcana: "major",
    uprightMeaning: "Love, harmony, relationships, values alignment, choices. A significant connection or a meaningful decision.",
    reversedMeaning: "Imbalance, misalignment, disharmony. A relationship or choice that lacks authenticity.",
    keywords: ["love", "union", "choice", "harmony", "values"],
    symbolism: "The angel above blesses the union. The tree of knowledge reminds us that love requires conscious choice.",
    love: "Deep connection based on shared values. A soulful partnership or important relationship decision.",
    career: "Choose work aligned with your values. Partnership opportunities arise.",
    personalGrowth: "Align your actions with your true values. Authenticity is the path.",
    reflectionQuestion: "What choice reflects my deepest values?",
    element: "Air",
    astrologicalSign: "Gemini",
  },
  {
    id: "the-chariot",
    name: "The Chariot",
    number: 7,
    arcana: "major",
    uprightMeaning: "Willpower, determination, success, ambition, control. Victory through focus and determination.",
    reversedMeaning: "Lack of control, aggression, no direction. Force without purpose leads nowhere.",
    keywords: ["victory", "willpower", "determination", "drive", "triumph"],
    symbolism: "The sphinxes represent opposing forces being directed. The starry crown connects to divine guidance.",
    love: "Take initiative in love. Determination and confidence attract what you desire.",
    career: "Success is within reach. Stay focused and drive forward.",
    personalGrowth: "Direct your energy with intention. You can overcome any obstacle.",
    reflectionQuestion: "What am I driving toward with full determination?",
    element: "Water",
    astrologicalSign: "Cancer",
  },
  {
    id: "strength",
    name: "Strength",
    number: 8,
    arcana: "major",
    uprightMeaning: "Courage, persuasion, influence, compassion, inner strength. True power comes from patience and gentleness.",
    reversedMeaning: "Self-doubt, weakness, insecurity, raw emotion. Struggling to find your inner courage.",
    keywords: ["courage", "patience", "compassion", "inner strength", "gentleness"],
    symbolism: "The woman gently closing the lion's mouth shows that true strength is soft. The infinity symbol echoes the Magician's power.",
    love: "Gentle patience heals. Compassion is stronger than force.",
    career: "Influence through kindness, not pressure. Your steady strength is your advantage.",
    personalGrowth: "Master your inner world. True strength is quiet and enduring.",
    reflectionQuestion: "Where can gentleness be my greatest strength?",
    element: "Fire",
    astrologicalSign: "Leo",
  },
  {
    id: "the-hermit",
    name: "The Hermit",
    number: 9,
    arcana: "major",
    uprightMeaning: "Soul-searching, introspection, solitude, inner guidance. Step back from the noise and seek wisdom within.",
    reversedMeaning: "Isolation, loneliness, withdrawal. Too much solitude becomes avoidance.",
    keywords: ["solitude", "wisdom", "introspection", "guidance", "searching"],
    symbolism: "The lantern contains the star of wisdom — inner light illuminates the path. The staff represents authority over one's own journey.",
    love: "Time alone clarifies what you truly need in love. Seek within before seeking without.",
    career: "Step back to see the bigger picture. Research and reflection before action.",
    personalGrowth: "Honor your need for solitude. The answers come in stillness.",
    reflectionQuestion: "What truth have I been avoiding in the quiet?",
    element: "Earth",
    astrologicalSign: "Virgo",
  },
  {
    id: "wheel-of-fortune",
    name: "Wheel of Fortune",
    number: 10,
    arcana: "major",
    uprightMeaning: "Good luck, karma, life cycles, destiny, a turning point. The wheel turns — change is coming.",
    reversedMeaning: "Bad luck, resistance to change, breaking cycles. Fighting the natural flow of life.",
    keywords: ["destiny", "change", "cycles", "luck", "turning point"],
    symbolism: "The wheel represents life's cycles. The four creatures at the corners symbolize the fixed signs of the zodiac.",
    love: "Fate brings a connection. Trust the timing of your heart.",
    career: "Opportunity arrives. Be ready to act when fortune favors you.",
    personalGrowth: "Accept the cycles of life. What rises will fall, and what falls will rise again.",
    reflectionQuestion: "What cycle is completing, and what is beginning?",
    element: "Fire",
    astrologicalSign: "Jupiter",
  },
  {
    id: "justice",
    name: "Justice",
    number: 11,
    arcana: "major",
    uprightMeaning: "Justice, fairness, truth, cause and effect, law. The truth will be revealed. Actions have consequences.",
    reversedMeaning: "Unfairness, dishonesty, lack of accountability. Something is not being judged fairly.",
    keywords: ["truth", "fairness", "balance", "accountability", "karma"],
    symbolism: "The sword cuts through illusion. The scales weigh all sides of a situation.",
    love: "Honesty and fairness strengthen a connection. Address imbalances directly.",
    career: "Fair outcomes. Legal matters resolve. Integrity is your guide.",
    personalGrowth: "Take responsibility for your choices. Truth liberates.",
    reflectionQuestion: "What truth am I being asked to face?",
    element: "Air",
    astrologicalSign: "Libra",
  },
  {
    id: "the-hanged-man",
    name: "The Hanged Man",
    number: 12,
    arcana: "major",
    uprightMeaning: "Surrender, letting go, new perspectives, pause. Sometimes doing nothing is the most powerful action.",
    reversedMeaning: "Delays, resistance, stalling, needless sacrifice. Hanging on when you need to let go.",
    keywords: ["surrender", "perspective", "pause", "letting go", "sacrifice"],
    symbolism: "The calm expression shows willingness, not punishment. The halo represents enlightenment gained through surrender.",
    love: "See the situation from a different angle. Patience reveals what action cannot.",
    career: "A pause before progress. Use this time to reassess your direction.",
    personalGrowth: "Release the need to control. Wisdom comes from stillness.",
    reflectionQuestion: "What would happen if I stopped resisting?",
    element: "Water",
    astrologicalSign: "Neptune",
  },
  {
    id: "death",
    name: "Death",
    number: 13,
    arcana: "major",
    uprightMeaning: "Endings, transformation, transition, letting go. One chapter closes so another can begin.",
    reversedMeaning: "Resistance to change, stagnation, decay. Holding on to what has already passed.",
    keywords: ["transformation", "endings", "rebirth", "transition", "release"],
    symbolism: "The white rose represents purity through transformation. The rising sun promises renewal after endings.",
    love: "A relationship transforms or ends. Something new is trying to be born.",
    career: "A career chapter ends. Embrace the transition — better opportunities await.",
    personalGrowth: "Let go of who you were. Become who you are meant to be.",
    reflectionQuestion: "What am I being asked to release so I can grow?",
    element: "Water",
    astrologicalSign: "Scorpio",
  },
  {
    id: "temperance",
    name: "Temperance",
    number: 14,
    arcana: "major",
    uprightMeaning: "Balance, moderation, patience, purpose, harmony. Find the middle path and blend opposing forces.",
    reversedMeaning: "Imbalance, excess, self-healing, realignment. Something is out of proportion.",
    keywords: ["balance", "moderation", "patience", "harmony", "alchemy"],
    symbolism: "The angel pouring water between cups represents the flow of life. One foot on land, one in water — grounding and emotion balanced.",
    love: "A balanced, harmonious connection. Patience and compromise deepen love.",
    career: "Balance competing demands. Steady progress through moderation.",
    personalGrowth: "Find harmony between all parts of yourself. Integration is the goal.",
    reflectionQuestion: "Where in my life do I need more balance?",
    element: "Fire",
    astrologicalSign: "Sagittarius",
  },
  {
    id: "the-devil",
    name: "The Devil",
    number: 15,
    arcana: "major",
    uprightMeaning: "Shadow self, attachment, addiction, restriction, materialism. What binds you? The chains are often self-imposed.",
    reversedMeaning: "Releasing limiting beliefs, exploring dark thoughts, detachment. Freedom is possible when you see the chains.",
    keywords: ["shadow", "attachment", "freedom", "temptation", "materialism"],
    symbolism: "The chains around the figures' necks are loose — they could remove them. Awareness of bondage is the first step to freedom.",
    love: "An intense but possibly unhealthy connection. Examine what truly binds you.",
    career: "Material success at what cost? Check if ambition serves your soul.",
    personalGrowth: "Face your shadows honestly. What you deny controls you.",
    reflectionQuestion: "What am I attached to that no longer serves me?",
    element: "Earth",
    astrologicalSign: "Capricorn",
  },
  {
    id: "the-tower",
    name: "The Tower",
    number: 16,
    arcana: "major",
    uprightMeaning: "Sudden upheaval, broken pride, disaster, revelation. Structures built on false foundations must fall.",
    reversedMeaning: "Personal transformation, fear of change, averting disaster. The storm can be weathered with awareness.",
    keywords: ["upheaval", "revelation", "awakening", "destruction", "liberation"],
    symbolism: "Lightning strikes the crown from the tower — false structures are demolished. The falling figures represent ego being humbled.",
    love: "A shake-up reveals the truth. Something unstable must fall for real love to grow.",
    career: "Unexpected changes. What seemed certain may shift. Adaptability is key.",
    personalGrowth: "Sometimes destruction is the foundation for rebuilding. Trust the process.",
    reflectionQuestion: "What false structure in my life needs to come down?",
    element: "Fire",
    astrologicalSign: "Mars",
  },
  {
    id: "the-star",
    name: "The Star",
    number: 17,
    arcana: "major",
    uprightMeaning: "Hope, faith, purpose, renewal, spirituality. After the storm, the stars appear. Healing is happening.",
    reversedMeaning: "Lack of faith, despair, self-trust issues, disconnection. The stars are still there, even when hidden.",
    keywords: ["hope", "healing", "renewal", "faith", "inspiration"],
    symbolism: "The woman pours water onto land and into the pool — nourishing both conscious and subconscious. The eight stars represent renewal.",
    love: "Hope returns to love. A healing connection or the mending of a wounded heart.",
    career: "Inspired creativity. Follow what lights you up inside.",
    personalGrowth: "Trust the universe. You are being guided even when you cannot see the way.",
    reflectionQuestion: "What gives me hope right now?",
    element: "Air",
    astrologicalSign: "Aquarius",
  },
  {
    id: "the-moon",
    name: "The Moon",
    number: 18,
    arcana: "major",
    uprightMeaning: "Illusion, fear, anxiety, subconscious, intuition. Things are not as they seem. Trust your instincts through uncertainty.",
    reversedMeaning: "Release of fear, repressed emotions, inner confusion clearing. The fog is lifting.",
    keywords: ["illusion", "intuition", "subconscious", "mystery", "uncertainty"],
    symbolism: "The path between the towers leads into the unknown. The crayfish emerging from the water represents the subconscious surfacing.",
    love: "Uncertainty in love. Not everything is as it appears. Trust your gut.",
    career: "Confusion about direction. Gather more information before making big decisions.",
    personalGrowth: "Face your fears honestly. The moon illuminates what hides in shadow.",
    reflectionQuestion: "What illusion am I ready to see through?",
    element: "Water",
    astrologicalSign: "Pisces",
  },
  {
    id: "the-sun",
    name: "The Sun",
    number: 19,
    arcana: "major",
    uprightMeaning: "Positivity, fun, warmth, success, vitality. Joy, achievement, and radiant energy. Everything is illuminated.",
    reversedMeaning: "Inner child issues, feeling down, overly optimistic. Temporary clouds遮住 the sun.",
    keywords: ["joy", "success", "vitality", "warmth", "abundance"],
    symbolism: "The child on the white horse represents innocent joy. The sunflowers turning toward the sun symbolize natural happiness.",
    love: "Pure happiness in love. A joyful, playful, warm connection.",
    career: "Success and recognition. Your efforts are rewarded with warmth.",
    personalGrowth: "Embrace joy without guilt. You deserve to shine.",
    reflectionQuestion: "What brings me pure, simple joy?",
    element: "Fire",
    astrologicalSign: "Sun",
  },
  {
    id: "judgement",
    name: "Judgement",
    number: 20,
    arcana: "major",
    uprightMeaning: "Judgement, rebirth, inner calling, absolution, reflection. A moment of reckoning and renewal. Answer your higher calling.",
    reversedMeaning: "Self-doubt, refusal of self-examination, failure to learn from the past. Ignoring the call.",
    keywords: ["rebirth", "calling", "reflection", "absolution", "awakening"],
    symbolism: "The angel's trumpet calls the figures from their graves — past experiences are resurrected with new understanding.",
    love: "A relationship reaches a turning point. Honest evaluation leads to renewal.",
    career: "A calling demands attention. The work you are meant to do is trying to find you.",
    personalGrowth: "Forgive yourself and others. Rise from the past with wisdom.",
    reflectionQuestion: "What calling have I been ignoring?",
    element: "Fire",
    astrologicalSign: "Pluto",
  },
  {
    id: "the-world",
    name: "The World",
    number: 21,
    arcana: "major",
    uprightMeaning: "Completion, integration, accomplishment, travel, wholeness. A major cycle completes. You have arrived.",
    reversedMeaning: "Incompletion, shortcuts, unfulfilled potential. Almost there — don't stop now.",
    keywords: ["completion", "wholeness", "achievement", "integration", "fulfillment"],
    symbolism: "The dancer holds two wands — mastery over both worlds. The wreath represents victory and completion of the journey.",
    love: "A complete, fulfilling partnership. The search is over — this is real.",
    career: "Major achievement. A project or phase reaches successful completion.",
    personalGrowth: "You are whole. The journey from Fool to World is complete — and ready to begin again.",
    reflectionQuestion: "What have I completed, and what new cycle awaits?",
    element: "Earth",
    astrologicalSign: "Saturn",
  },
];
