import { TarotCard } from "./types";
import { MAJOR_ARCANA } from "./major-arcana";

export { MAJOR_ARCANA } from "./major-arcana";

export const CUPS: TarotCard[] = [
  {
    id: "ace-of-cups",
    name: "Ace of Cups",
    number: 1,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "New feelings, emotional awakening, creativity, love, intuition. A new emotional chapter begins.",
    reversedMeaning: "Emotional loss, blocked creativity, emptiness. Feelings that cannot flow freely.",
    keywords: ["new love", "emotion", "creativity", "intuition", "compassion"],
    symbolism: "The overflowing cup represents emotional abundance. The five streams of water represent the five senses being nourished.",
    love: "A new emotional beginning. Love is trying to enter your life.",
    career: "Creative inspiration flows. A new passion project begins.",
    personalGrowth: "Open your heart. New emotional experiences await.",
    reflectionQuestion: "What new feeling is emerging in my life?",
    element: "Water",
  },
  {
    id: "two-of-cups",
    name: "Two of Cups",
    number: 2,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "Unified love, partnership, mutual attraction, connection. A beautiful bond between two people.",
    reversedMeaning: "Break-up, imbalance in a relationship, tension. A connection that has lost its harmony.",
    keywords: ["partnership", "connection", "harmony", "attraction", "balance"],
    symbolism: "Two figures exchange cups in a ceremony of mutual respect. The caduceus above represents balanced partnership.",
    love: "A deep, balanced connection. Partnership and mutual respect flourish.",
    career: "A beneficial partnership or collaboration. Working together brings results.",
    personalGrowth: "Honor the connections that nourish you. Reciprocity is sacred.",
    reflectionQuestion: "What partnership in my life deserves more attention?",
    element: "Water",
  },
  {
    id: "three-of-cups",
    name: "Three of Cups",
    number: 3,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "Celebration, friendship, creativity, community, collaboration. Joy shared with others.",
    reversedMeaning: "Overindulgence, gossip, isolation. Celebration that has lost its meaning.",
    keywords: ["celebration", "friendship", "community", "joy", "collaboration"],
    symbolism: "Three women raise their cups in a toast. Flowers and fruit represent the abundance that comes from togetherness.",
    love: "A relationship celebrated by friends and community. Social joy around love.",
    career: "Team success. Celebrate achievements with those who helped you get there.",
    personalGrowth: "Surround yourself with people who celebrate you. Community heals.",
    reflectionQuestion: "Who am I celebrating life with?",
    element: "Water",
  },
  {
    id: "four-of-cups",
    name: "Four of Cups",
    number: 4,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "Meditation, contemplation, apathy, reevaluation. Looking inward because the outside world feels insufficient.",
    reversedMeaning: "Retreat, withdrawal, checking in with yourself. A new perspective emerging from contemplation.",
    keywords: ["contemplation", "apathy", "reevaluation", "meditation", "discontent"],
    symbolism: "A figure sits under a tree, ignoring a cup offered by a cloud. The focus is on inner experience, not outer gifts.",
    love: "Emotional withdrawal or boredom. What are you taking for granted?",
    career: "Lack of motivation. Reconnect with what excites you about your work.",
    personalGrowth: "Look deeper. What you seek may already be in front of you.",
    reflectionQuestion: "What opportunity am I overlooking?",
    element: "Water",
  },
  {
    id: "five-of-cups",
    name: "Five of Cups",
    number: 5,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "Regret, failure, disappointment, pessimism, loss. Grief over what has been lost — but not all is gone.",
    reversedMeaning: "Personal setbacks overcome, self-forgiveness, moving on. Finding what remains after loss.",
    keywords: ["loss", "grief", "regret", "disappointment", "moving on"],
    symbolism: "Three cups are spilled, but two remain standing. The figure mourns what is lost rather than seeing what endures.",
    love: "Disappointment in love. But hope remains — do not close your heart.",
    career: "A setback stings. Learn from it and focus on what still works.",
    personalGrowth: "Honor your grief, then turn around. There is still much to be grateful for.",
    reflectionQuestion: "What can I learn from this disappointment?",
    element: "Water",
  },
  {
    id: "six-of-cups",
    name: "Six of Cups",
    number: 6,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "Revisiting the past, childhood memories, innocence, joy, reunion. A return to simpler times.",
    reversedMeaning: "Living in the past, forgiveness needed, naivety. Nostalgia that prevents growth.",
    keywords: ["nostalgia", "innocence", "memories", "reunion", "childhood"],
    symbolism: "A child offers a cup of flowers to another. The tower in the background represents security and home.",
    love: "A reunion with someone from your past. Childhood sweetness returns.",
    career: "Returning to something you once loved. Past experience serves you now.",
    personalGrowth: "Honor where you came from, but don't live there. Integrate the past with the present.",
    reflectionQuestion: "What memory is asking for my attention?",
    element: "Water",
  },
  {
    id: "seven-of-cups",
    name: "Seven of Cups",
    number: 7,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "Fantasy, illusion, wishful thinking, choices, imagination. Many options appear — but which are real?",
    reversedMeaning: "Alignment, personal values, overwhelmed by choices. Clarity emerging from confusion.",
    keywords: ["illusion", "choices", "fantasy", "imagination", "decisions"],
    symbolism: "Seven cups float in clouds, each containing a different vision. Not all fantasies can become reality.",
    love: "Too many fantasies about love. Ground yourself in what is real.",
    career: "Many possibilities. Choose one and commit rather than chasing them all.",
    personalGrowth: "Dreams are beautiful, but action makes them real. Choose wisely.",
    reflectionQuestion: "Which of my dreams am I ready to pursue?",
    element: "Water",
  },
  {
    id: "eight-of-cups",
    name: "Eight of Cups",
    number: 8,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "Disappointment, abandonment, withdrawal, escapism. Walking away from something that no longer fulfills you.",
    reversedMeaning: "Trying one more time, indecision, aimless drifting. Staying when you know it is time to go.",
    keywords: ["departure", "withdrawal", "letting go", "searching", "moving on"],
    symbolism: "A figure walks away from eight neatly stacked cups toward the mountains. The journey inward has begun.",
    love: "Walking away from an unfulfilling connection. You deserve more.",
    career: "Leaving a situation that no longer serves your growth. Better things await.",
    personalGrowth: "Sometimes the bravest thing is to walk away. Trust the journey ahead.",
    reflectionQuestion: "What am I ready to leave behind?",
    element: "Water",
  },
  {
    id: "nine-of-cups",
    name: "Nine of Cups",
    number: 9,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "Contentment, satisfaction, gratitude, wish come true, emotional fulfillment. The wish card — what you desire is within reach.",
    reversedMeaning: "Inner happiness, materialism, dissatisfaction. Seeking fulfillment in the wrong places.",
    keywords: ["wishes", "contentment", "gratitude", "fulfillment", "satisfaction"],
    symbolism: "A figure sits comfortably before nine cups arranged on a shelf. Emotional satisfaction is achieved.",
    love: "Deep emotional satisfaction. A wish in love is granted.",
    career: "Professional fulfillment. Your efforts have created something meaningful.",
    personalGrowth: "Gratitude amplifies joy. Appreciate what you have built.",
    reflectionQuestion: "What wish has come true that I should celebrate?",
    element: "Water",
  },
  {
    id: "ten-of-cups",
    name: "Ten of Cups",
    number: 10,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "Divine love, harmony, alignment, family, happiness. Emotional fulfillment that extends beyond yourself to those you love.",
    reversedMeaning: "Misaligned values, broken family, disconnection. The image of happiness without the substance.",
    keywords: ["harmony", "family", "love", "happiness", "fulfillment"],
    symbolism: "A couple raises their arms toward a rainbow of ten cups. Children dance nearby. Emotional abundance is shared.",
    love: "A loving, stable, harmonious relationship. Family and emotional security.",
    career: "Work that aligns with your values. Success that benefits those you love.",
    personalGrowth: "True happiness is shared. Build what nourishes the heart.",
    reflectionQuestion: "What does my version of emotional fulfillment look like?",
    element: "Water",
  },
  {
    id: "page-of-cups",
    name: "Page of Cups",
    number: 11,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "Creative opportunity, intuitive messages, curiosity, wonder. A surprising message or creative spark arrives.",
    reversedMeaning: "Emotional immaturity, insecurity, creative block. Feelings that are hard to express.",
    keywords: ["creativity", "intuition", "curiosity", "wonder", "messages"],
    symbolism: "A young person holds a cup from which a fish appears — unexpected creative inspiration from the subconscious.",
    love: "A sweet, innocent message or gesture. New feelings emerging.",
    career: "A creative opportunity. Follow your curiosity.",
    personalGrowth: "Stay open to wonder. The world is trying to surprise you.",
    reflectionQuestion: "What creative impulse is trying to emerge?",
    element: "Water",
  },
  {
    id: "knight-of-cups",
    name: "Knight of Cups",
    number: 12,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "Creativity, romance, charm, imagination, beauty. A messenger of the heart bringing emotional offers.",
    reversedMeaning: "Overactive imagination, unrealistic, jealousy. Feelings that overwhelm reason.",
    keywords: ["romance", "charm", "creativity", "imagination", "idealism"],
    symbolism: "A knight in armor rides gracefully, holding a cup extended forward. Emotional offers arrive with style.",
    love: "A romantic gesture or offer of love. Someone is captivated by you.",
    career: "A creative opportunity approaches. Follow your heart with open eyes.",
    personalGrowth: "Balance dreams with action. Romance your own life.",
    reflectionQuestion: "What emotional offer am I ready to receive?",
    element: "Water",
  },
  {
    id: "queen-of-cups",
    name: "Queen of Cups",
    number: 13,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "Compassionate, caring, emotionally stable, intuitive, nurturing. A deep well of emotional wisdom.",
    reversedMeaning: "Inner feelings, self-care needed, co-dependency. Giving too much to others, neglecting yourself.",
    keywords: ["compassion", "intuition", "nurturing", "emotional wisdom", "empathy"],
    symbolism: "A queen sits on a throne at the water's edge, holding a closed ornate cup. Emotions are deep but contained.",
    love: "A deeply nurturing, emotionally intelligent partner or energy.",
    career: "Lead with empathy. Your emotional intelligence is your strength.",
    personalGrowth: "Nurture yourself as you nurture others. Your sensitivity is a gift.",
    reflectionQuestion: "How well am I caring for my emotional self?",
    element: "Water",
  },
  {
    id: "king-of-cups",
    name: "King of Cups",
    number: 14,
    arcana: "minor",
    suit: "cups",
    uprightMeaning: "Emotionally balanced, compassionate, diplomatic, wise. Mastery over feelings without suppression.",
    reversedMeaning: "Self-compassion deficit, inner feelings, moodiness. Emotions that control rather than inform.",
    keywords: ["emotional balance", "diplomacy", "wisdom", "compassion", "mastery"],
    symbolism: "A king sits on a throne amidst turbulent waters but remains calm. Emotional mastery in the midst of storms.",
    love: "A partner who is emotionally mature, supportive, and wise.",
    career: "Diplomatic leadership. Navigate complex situations with emotional intelligence.",
    personalGrowth: "Mastery of emotions is not suppression — it is understanding and choosing your response.",
    reflectionQuestion: "How can I lead with both wisdom and compassion?",
    element: "Water",
  },
];

export const WANDS: TarotCard[] = [
  {
    id: "ace-of-wands",
    name: "Ace of Wands",
    number: 1,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Inspiration, new opportunities, growth, potential, creative spark. A powerful new beginning fueled by passion.",
    reversedMeaning: "Delays, lack of direction, distractions. The spark exists but is not being nurtured.",
    keywords: ["inspiration", "creativity", "potential", "passion", "new beginnings"],
    symbolism: "A hand reaches from a cloud holding a wand sprouting new leaves. The landscape below is fertile and promising.",
    love: "A passionate new connection or creative spark in an existing relationship.",
    career: "A new opportunity ignites your passion. This is the beginning of something exciting.",
    personalGrowth: "What lights your fire? Follow the spark of inspiration.",
    reflectionQuestion: "What new inspiration is trying to take root in my life?",
    element: "Fire",
  },
  {
    id: "two-of-wands",
    name: "Two of Wands",
    number: 2,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Future planning, progress, decisions, discovery, personal power. The world is waiting — make your plan.",
    reversedMeaning: "Fear of change, playing it safe, bad planning. Overthinking instead of acting.",
    keywords: ["planning", "decisions", "discovery", "progress", "vision"],
    symbolism: "A figure holds a globe while standing between two wands. The world is within reach — the planning stage before action.",
    love: "Thinking about the future of a relationship. Where do you want this to go?",
    career: "Planning your next move. Big decisions about direction are ahead.",
    personalGrowth: "Hold the vision of your life in your hands. Then take the first step.",
    reflectionQuestion: "What future am I ready to plan for?",
    element: "Fire",
  },
  {
    id: "three-of-wands",
    name: "Three of Wands",
    number: 3,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Progress, expansion, foresight, overseas opportunities, momentum. Your plans are beginning to take shape.",
    reversedMeaning: "Obstacles, delays, frustration, setbacks. Plans that hit unexpected resistance.",
    keywords: ["expansion", "progress", "foresight", "opportunity", "momentum"],
    symbolism: "A figure watches ships sail toward the horizon. Expansion and opportunity are on their way.",
    love: "A relationship is growing and expanding. New horizons together.",
    career: "Growth and expansion. International or broader opportunities appear.",
    personalGrowth: "Look beyond the immediate. Your vision is expanding.",
    reflectionQuestion: "What opportunity is approaching from the horizon?",
    element: "Fire",
  },
  {
    id: "four-of-wands",
    name: "Four of Wands",
    number: 4,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Celebration, harmony, home, community, joy. A milestone worth celebrating with those you love.",
    reversedMeaning: "Personal celebration, inner harmony, conflict with others. Finding peace within even when outside is unsettled.",
    keywords: ["celebration", "home", "harmony", "community", "milestone"],
    symbolism: "Four wands form a canopy decorated with flowers. People celebrate in the background. Home and community unite.",
    love: "A stable, joyful relationship celebrated by those around you.",
    career: "Reaching a milestone. Celebrate your achievements with your team.",
    personalGrowth: "Create spaces of joy and belonging. You deserve to celebrate.",
    reflectionQuestion: "What milestone am I ready to celebrate?",
    element: "Fire",
  },
  {
    id: "five-of-wands",
    name: "Five of Wands",
    number: 5,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Conflict, disagreements, competition, tension, diversity of opinion. Multiple voices create friction — but also growth.",
    reversedMeaning: "Inner conflict, avoiding conflict, peace after struggle. Finding resolution or choosing your battles.",
    keywords: ["conflict", "competition", "tension", "challenge", "debate"],
    symbolism: "Five figures each hold a wand in different directions. No one is aligned — but everyone has a voice.",
    love: "Disagreements or competition in love. Work through the tension honestly.",
    career: "Competition or workplace friction. Use it as fuel, not frustration.",
    personalGrowth: "Conflict can be constructive. What is this tension teaching you?",
    reflectionQuestion: "What conflict am I being asked to engage with honestly?",
    element: "Fire",
  },
  {
    id: "six-of-wands",
    name: "Six of Wands",
    number: 6,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Victory, success, public recognition, progress, self-confidence. Your efforts are acknowledged and celebrated.",
    reversedMeaning: "Private achievement, fall from grace, egotism. Success that comes with hidden costs.",
    keywords: ["victory", "success", "recognition", "confidence", "triumph"],
    symbolism: "A figure rides triumphantly through a crowd, carrying a wand adorned with a laurel wreath. Public victory is achieved.",
    love: "A relationship that feels like a victory. Mutual admiration and pride.",
    career: "Public recognition for your work. A well-deserved success.",
    personalGrowth: "Celebrate your wins. You earned this moment.",
    reflectionQuestion: "What victory am I ready to acknowledge?",
    element: "Fire",
  },
  {
    id: "seven-of-wands",
    name: "Seven of Wands",
    number: 7,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Challenge, competition, protection, perseverance, defense. Standing your ground when others push against you.",
    reversedMeaning: "Exhaustion, giving up, overwhelmed. The fight feels too hard — but is it?",
    keywords: ["challenge", "defense", "perseverance", "courage", "standing ground"],
    symbolism: "A figure stands on high ground, defending their position with a wand against six others coming from below.",
    love: "Defending a relationship against outside pressure. Standing together.",
    career: "Holding your position against competition. Perseverance pays off.",
    personalGrowth: "What is worth fighting for? Stand your ground on what matters.",
    reflectionQuestion: "What am I being called to defend?",
    element: "Fire",
  },
  {
    id: "eight-of-wands",
    name: "Eight of Wands",
    number: 8,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Speed, action, air travel, movement, swift change. Things are moving fast — stay ready.",
    reversedMeaning: "Delays, frustration, waiting, slowdown. Momentum blocked or scattered energy.",
    keywords: ["speed", "action", "movement", "progress", "swift change"],
    symbolism: "Eight wands fly through a clear sky with no obstacles. Unimpeded progress and rapid movement.",
    love: "Things move quickly in love. Exciting developments are on their way.",
    career: "Rapid progress. Projects accelerate and come together swiftly.",
    personalGrowth: "When momentum comes, ride it. Do not hesitate.",
    reflectionQuestion: "What is moving quickly in my life that I should embrace?",
    element: "Fire",
  },
  {
    id: "nine-of-wands",
    name: "Nine of Wands",
    number: 9,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Resilience, grit, last stand, persistence, boundaries. You have been through much — do not give up now.",
    reversedMeaning: "Exhaustion, fatigue, defensiveness, paranoia. Worn down by too many battles.",
    keywords: ["resilience", "persistence", "courage", "boundaries", "last push"],
    symbolism: "A weary figure leans on a wand, eight others standing behind them as a defensive wall. Resilience through experience.",
    love: "A relationship tested by time. Persistence and boundaries are needed.",
    career: "The final push before success. Keep going — you are almost there.",
    personalGrowth: "Your struggles have made you strong. Do not abandon what you have built.",
    reflectionQuestion: "What have my struggles taught me that I can use now?",
    element: "Fire",
  },
  {
    id: "ten-of-wands",
    name: "Ten of Wands",
    number: 10,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Burden, extra responsibility, hard work, completion, stress. Carrying too much — but the end is near.",
    reversedMeaning: "Releasing burdens, delegation, overwhelm. Learning to put some of the weight down.",
    keywords: ["burden", "responsibility", "hard work", "stress", "completion"],
    symbolism: "A figure carries ten heavy wands toward a town in the distance. The load is heavy but the destination is visible.",
    love: "Taking on too much in a relationship. Share the load with your partner.",
    career: "Heavy workload. Delegate what you can and focus on what matters most.",
    personalGrowth: "You do not have to carry everything alone. Ask for help.",
    reflectionQuestion: "What burden am I ready to put down?",
    element: "Fire",
  },
  {
    id: "page-of-wands",
    name: "Page of Wands",
    number: 11,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Enthusiasm, exploration, discovery, free spirit, adventure. A youthful energy ready to explore new territory.",
    reversedMeaning: "Newly formed ideas, redirecting energy, self-expression limits. Enthusiasm that lacks direction.",
    keywords: ["enthusiasm", "exploration", "adventure", "discovery", "passion"],
    symbolism: "A young figure gazes at a wand sprouting new leaves, with a desert landscape behind. Adventure beckons.",
    love: "A new, exciting connection. Adventure and discovery in love.",
    career: "A new project or role ignites your enthusiasm. Explore freely.",
    personalGrowth: "Approach life with fresh eyes. Curiosity is your compass.",
    reflectionQuestion: "What adventure is calling to me?",
    element: "Fire",
  },
  {
    id: "knight-of-wands",
    name: "Knight of Wands",
    number: 12,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Energy, passion, inspired action, adventure, impulsiveness. Charging forward with enthusiasm and courage.",
    reversedMeaning: "Haste, scattered energy, delays in travel, frustration. Passion without patience.",
    keywords: ["energy", "passion", "adventure", "action", "courage"],
    symbolism: "A knight rides a rearing horse, wand raised high. Dynamic energy and fearless forward motion.",
    love: "An exciting, passionate connection. Things move quickly and intensely.",
    career: "Bold action and risk-taking. Channel your energy wisely.",
    personalGrowth: "Charge toward what excites you. Just remember to look where you are going.",
    reflectionQuestion: "What bold action am I ready to take?",
    element: "Fire",
  },
  {
    id: "queen-of-wands",
    name: "Queen of Wands",
    number: 13,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Courage, confidence, independence, determination, warmth, vitality. A magnetic presence that inspires others.",
    reversedMeaning: "Selfishness, jealousy, insecure, demanding. Confidence that has become brittle or controlling.",
    keywords: ["confidence", "courage", "warmth", "independence", "magnetism"],
    symbolism: "A queen sits on a throne adorned with lions and sunflowers, holding a wand and a black cat at her feet. Bold and intuitive.",
    love: "A confident, warm, passionate partner or energy. Magnetic attraction.",
    career: "Lead with confidence and warmth. Your presence inspires those around you.",
    personalGrowth: "Own your power without apology. The world needs your light.",
    reflectionQuestion: "How can I embody my confidence more fully?",
    element: "Fire",
  },
  {
    id: "king-of-wands",
    name: "King of Wands",
    number: 14,
    arcana: "minor",
    suit: "wands",
    uprightMeaning: "Natural-born leader, vision, entrepreneur, honor, bold decisions. Leading with vision and integrity.",
    reversedMeaning: "Impulsive, overbearing, unrealistic expectations, high expectations. Leadership without empathy.",
    keywords: ["leadership", "vision", "entrepreneur", "bold", "integrity"],
    symbolism: "A king sits on a throne decorated with lions and salamanders, holding a wand and a globe. Visionary leadership.",
    love: "A bold, confident, visionary partner. Leadership in love with warmth.",
    career: "Take bold, visionary action. Your leadership is needed.",
    personalGrowth: "Lead your own life with vision and courage. Your dreams are valid.",
    reflectionQuestion: "What vision am I being called to lead toward?",
    element: "Fire",
  },
];

export const SWORDS: TarotCard[] = [
  {
    id: "ace-of-swords",
    name: "Ace of Swords",
    number: 1,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "Breakthrough, clarity, sharp mind, truth, new ideas. A moment of clear thinking and mental power.",
    reversedMeaning: "Inner clarity, re-think an idea, confusion, misuse of power. Mental clarity blocked by noise.",
    keywords: ["clarity", "truth", "breakthrough", "mental power", "new ideas"],
    symbolism: "A hand rises from a cloud holding a sword crowned with a wreath. Truth cuts through all illusion.",
    love: "Honest communication clears the air. Truth strengthens connection.",
    career: "A breakthrough idea. Clarity of thought leads to decisive action.",
    personalGrowth: "Cut through confusion with honest thinking. The truth sets you free.",
    reflectionQuestion: "What truth is trying to break through in my mind?",
    element: "Air",
  },
  {
    id: "two-of-swords",
    name: "Two of Swords",
    number: 2,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "Difficult decisions, avoidance, stalemate, painful choices, indecision. A choice that cannot be avoided forever.",
    reversedMeaning: "Indecision, confusion, information overload, release. The stalemate is breaking.",
    keywords: ["decisions", "indecision", "stalemate", "balance", "choices"],
    symbolism: "A blindfolded figure holds two crossed swords over water. Emotional information is blocked by mental avoidance.",
    love: "A difficult choice in love. The heart knows what the mind resists.",
    career: "A stalemate at work. Gather information and make a choice.",
    personalGrowth: "The blindfold must come off. Face what you are avoiding.",
    reflectionQuestion: "What decision have I been postponing?",
    element: "Air",
  },
  {
    id: "three-of-swords",
    name: "Three of Swords",
    number: 3,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "Heartbreak, emotional pain, sorrow, grief, hurtful words. Painful truth that must be acknowledged.",
    reversedMeaning: "Recovery, forgiveness, releasing pain, optimism. Healing after heartbreak.",
    keywords: ["heartbreak", "sorrow", "grief", "pain", "truth"],
    symbolism: "Three swords pierce a heart floating in storm clouds. Emotional pain that words and thoughts have caused.",
    love: "Heartbreak or painful words. Allow yourself to grieve — healing follows.",
    career: "Painful truth at work. Accept it and move forward with clarity.",
    personalGrowth: "Honor your pain. It is teaching you about what matters most.",
    reflectionQuestion: "What heartbreak am I ready to heal from?",
    element: "Air",
  },
  {
    id: "four-of-swords",
    name: "Four of Swords",
    number: 4,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "Rest, relaxation, meditation, contemplation, recovery. A necessary pause to recharge mind and spirit.",
    reversedMeaning: "Exhaustion, burn-out, stagnation, need for solitude. The mind needs rest.",
    keywords: ["rest", "recovery", "meditation", "contemplation", "peace"],
    symbolism: "A figure lies in repose on a tomb, three swords on the wall, one beneath. Mental rest and spiritual preparation.",
    love: "Take time apart to reflect. Space can strengthen a connection.",
    career: "A break from mental exertion. Rest before the next challenge.",
    personalGrowth: "Stillness is not weakness. Rest is preparation for action.",
    reflectionQuestion: "What would happen if I truly rested?",
    element: "Air",
  },
  {
    id: "five-of-swords",
    name: "Five of Swords",
    number: 5,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "Conflict, disagreements, competition, defeat, winning at all costs. Victory that comes with a price.",
    reversedMeaning: "Reconciliation, making amends, past resentment, lingering conflict. Choosing peace over winning.",
    keywords: ["conflict", "defeat", "competition", "pride", "dishonor"],
    symbolism: "A figure holds three swords while two others walk away. Some victories are hollow.",
    love: "Arguments that damage the connection. Is being right worth the cost?",
    career: "Workplace conflict. Winning this battle may lose the war.",
    personalGrowth: "Choose your battles wisely. Not every fight is worth having.",
    reflectionQuestion: "What conflict am I choosing that costs too much?",
    element: "Air",
  },
  {
    id: "six-of-swords",
    name: "Six of Swords",
    number: 6,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "Transition, change, rite of passage, releasing baggage, moving on. Leaving troubled waters for calmer ones.",
    reversedMeaning: "Personal transition, resistance, unfinished business, unable to move on. The journey is delayed.",
    keywords: ["transition", "moving on", "healing", "journey", "recovery"],
    symbolism: "A figure ferries a woman and child across rough waters toward calm. Leaving difficulty behind.",
    love: "Moving away from difficulty in love. Healing and calmer waters ahead.",
    career: "A transition to a better situation. Leaving challenges behind.",
    personalGrowth: "The hardest part of the journey is the departure. You are already on your way.",
    reflectionQuestion: "What am I ready to leave behind as I move forward?",
    element: "Air",
  },
  {
    id: "seven-of-swords",
    name: "Seven of Swords",
    number: 7,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "Deception, trickery, tactics, strategy, resourcefulness. Not everything is as it seems — including your own actions.",
    reversedMeaning: "Coming clean, rethinking approach, conscience, deception revealed. The truth surfaces.",
    keywords: ["deception", "strategy", "stealth", "cunning", "dishonesty"],
    symbolism: "A figure sneaks away from a camp carrying five swords, leaving two behind. A partial theft — partial success.",
    love: "Dishonesty or half-truths. Full honesty is needed for trust.",
    career: "Office politics or strategy. Be careful about how you play the game.",
    personalGrowth: "Are you being honest with yourself? Self-deception is the hardest to see.",
    reflectionQuestion: "Where am I not being fully honest?",
    element: "Air",
  },
  {
    id: "eight-of-swords",
    name: "Eight of Swords",
    number: 8,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "Imprisonment, entrapment, self-victimization, restriction, powerlessness. The bonds may be largely mental.",
    reversedMeaning: "Self-acceptance, new perspective, freedom, release. Recognizing that the prison door is open.",
    keywords: ["restriction", "imprisonment", "powerlessness", "self-limitation", "awakening"],
    symbolism: "A blindfolded and bound figure stands among eight swords in water. The restriction is largely self-imposed and mental.",
    love: "Feeling trapped in a situation. The way out may be clearer than you think.",
    career: "Feeling stuck at work. Challenge the assumptions that bind you.",
    personalGrowth: "Your limitations may be stories you tell yourself. Test them.",
    reflectionQuestion: "What self-imposed limitation am I ready to release?",
    element: "Air",
  },
  {
    id: "nine-of-swords",
    name: "Nine of Swords",
    number: 9,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "Anxiety, worry, fear, depression, nightmares, negative thinking. The mind tormenting itself in the dark hours.",
    reversedMeaning: "Inner turmoil, deep-seated fears, hope emerging, light at end of tunnel. The worst is passing.",
    keywords: ["anxiety", "worry", "fear", "nightmares", "overthinking"],
    symbolism: "A figure sits up in bed, head in hands, nine swords on the wall. Mental anguish in the quiet of night.",
    love: "Anxiety about a relationship. The fears may be worse than reality.",
    career: "Worry and stress about work. Challenge catastrophic thinking.",
    personalGrowth: "Your worst fears are often not reality. Reach out — you do not have to suffer alone.",
    reflectionQuestion: "What fear is my mind amplifying beyond reality?",
    element: "Air",
  },
  {
    id: "ten-of-swords",
    name: "Ten of Swords",
    number: 10,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "Painful endings, deep wounds, betrayal, loss, crisis, rock bottom. The worst is over — only upward from here.",
    reversedMeaning: "Recovery, regeneration, resisting an inevitable end, surviving. The dawn after the darkest night.",
    keywords: ["ending", "rock bottom", "betrayal", "loss", "renewal"],
    symbolism: "A figure lies face down with ten swords in their back, but the horizon shows a new dawn. Endings precede beginnings.",
    love: "A painful ending. But from this ending, something new and better can grow.",
    career: "A difficult ending at work. The only way now is forward and up.",
    personalGrowth: "When you have nothing left to lose, you are free to rebuild everything.",
    reflectionQuestion: "What ending is making space for a new beginning?",
    element: "Air",
  },
  {
    id: "page-of-swords",
    name: "Page of Swords",
    number: 11,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "New ideas, curiosity, thirst for knowledge, new communication, vigilance. A sharp mind eager to learn.",
    reversedMeaning: "Self-expression issues, hurtful words, haste, all talk. Thinking without acting.",
    keywords: ["curiosity", "ideas", "communication", "learning", "vigilance"],
    symbolism: "A young figure stands with sword raised, clouds and wind blowing. Mental energy and alertness.",
    love: "New conversations and intellectual connection. Words matter now.",
    career: "A new idea or area of study. Approach with curiosity and open-mindedness.",
    personalGrowth: "Stay curious. Ask questions. The world is full of things to learn.",
    reflectionQuestion: "What new idea or area of knowledge excites me?",
    element: "Air",
  },
  {
    id: "knight-of-swords",
    name: "Knight of Swords",
    number: 12,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "Ambitious, action-oriented, driven, perfectionist, fast-thinking. Charging forward with mental energy and determination.",
    reversedMeaning: "Impulsive, burnout, self-sabotage, overly aggressive. Rushing in without thinking.",
    keywords: ["ambition", "action", "drive", "determination", "speed"],
    symbolism: "A knight charges forward on a galloping horse, sword raised, clouds swirling. Swift and determined mental action.",
    love: "Direct, honest communication. Swift action in matters of the heart.",
    career: "Ambitious drive toward your goals. Channel the energy productively.",
    personalGrowth: "Move fast, but do not forget to think. Speed without direction is chaos.",
    reflectionQuestion: "Where am I charging forward — and where should I pause?",
    element: "Air",
  },
  {
    id: "queen-of-swords",
    name: "Queen of Swords",
    number: 13,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "Independent, clear boundaries, direct communication, fair, perceptive. Wisdom born from experience, including painful ones.",
    reversedMeaning: "Cold-hearted, cruel, bitterness, overly emotional. Pain that has hardened into walls.",
    keywords: ["independence", "clarity", "boundaries", "wisdom", "directness"],
    symbolism: "A queen sits on a throne with clouds, a sword pointed skyward, one hand extended. Clear judgment and fair boundaries.",
    love: "Honest, direct communication. Boundaries that protect without closing off.",
    career: "Clear thinking and fair judgment. Direct communication serves you.",
    personalGrowth: "Your experiences have given you wisdom. Use it with compassion.",
    reflectionQuestion: "What boundary do I need to set or maintain?",
    element: "Air",
  },
  {
    id: "king-of-swords",
    name: "King of Swords",
    number: 14,
    arcana: "minor",
    suit: "swords",
    uprightMeaning: "Mental clarity, intellectual power, authority, truth, fairness. Leading with clear thinking and integrity.",
    reversedMeaning: "Manipulation, cruelty, abuse of power, coldness. Intelligence without compassion.",
    keywords: ["clarity", "authority", "truth", "intellect", "fairness"],
    symbolism: "A king sits on his throne, sword upright, butterflies and clouds carved into the seat. Intellectual authority and clarity.",
    love: "A partner who values honesty and direct communication. Mental connection.",
    career: "Leadership through clear thinking. Fair and decisive authority.",
    personalGrowth: "Master your mind without hardening your heart. Intelligence serves best when paired with compassion.",
    reflectionQuestion: "How can I use my mind in service of what is right?",
    element: "Air",
  },
];

export const PENTACLES: TarotCard[] = [
  {
    id: "ace-of-pentacles",
    name: "Ace of Pentacles",
    number: 1,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "New financial opportunity, prosperity, abundance, security, new venture. A solid new beginning in the material world.",
    reversedMeaning: "Lost opportunity, lack of planning, lack of resources. Missed financial beginnings.",
    keywords: ["opportunity", "prosperity", "abundance", "security", "manifestation"],
    symbolism: "A hand extends from a cloud holding a golden pentacle above a lush garden. Material abundance is being offered.",
    love: "A stable, secure new connection. Practical foundations for lasting love.",
    career: "A new financial opportunity. Plant the seed for long-term prosperity.",
    personalGrowth: "Ground your dreams in practical action. Abundance follows intention.",
    reflectionQuestion: "What new opportunity for abundance is presenting itself?",
    element: "Earth",
  },
  {
    id: "two-of-pentacles",
    name: "Two of Pentacles",
    number: 2,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "Multiple priorities, time management, prioritization, adaptability, juggling. Managing competing demands with grace.",
    reversedMeaning: "Over-committed, disorganization, financial instability, overwhelm. Too many balls in the air.",
    keywords: ["balance", "juggling", "adaptability", "priorities", "flexibility"],
    symbolism: "A figure juggles two pentacles connected by an infinite loop. The sea behind them rises and falls — change is constant.",
    love: "Balancing a relationship with other life demands. Adaptability is key.",
    career: "Juggling multiple projects or responsibilities. Prioritize and stay flexible.",
    personalGrowth: "Balance is a dynamic act, not a static state. Keep adjusting.",
    reflectionQuestion: "What am I juggling, and what deserves my priority?",
    element: "Earth",
  },
  {
    id: "three-of-pentacles",
    name: "Three of Pentacles",
    number: 3,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "Teamwork, collaboration, learning, implementation, skilled work. Working together toward a shared goal.",
    reversedMeaning: "Disharmony, misalignment, working alone, lack of skills. Collaboration that has broken down.",
    keywords: ["teamwork", "collaboration", "skill", "craftsmanship", "planning"],
    symbolism: "A craftsman works on a cathedral while two others consult plans. Skilled collaboration builds something meaningful.",
    love: "Building something together. A partnership based on shared effort and skill.",
    career: "Collaborative success. Your skills combined with others create excellence.",
    personalGrowth: "Learn from those with different skills. Growth comes through collaboration.",
    reflectionQuestion: "Who can I collaborate with to build something meaningful?",
    element: "Earth",
  },
  {
    id: "four-of-pentacles",
    name: "Four of Pentacles",
    number: 4,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "Saving, security, conservatism, scarcity mindset, control, boundaries. Holding tightly to what you have.",
    reversedMeaning: "Over-spending, generosity, letting go, releasing control. Finding balance between saving and living.",
    keywords: ["security", "control", "saving", "boundaries", "possessiveness"],
    symbolism: "A figure clutches a pentacle to their chest, stands on one, and has two at their feet. Gripping tightly to material security.",
    love: "Holding on too tightly. Security is important, but so is freedom.",
    career: "Financial caution. Protecting what you have built. But watch for scarcity thinking.",
    personalGrowth: "What are you gripping so tightly that it prevents growth?",
    reflectionQuestion: "Am I holding on out of security or fear?",
    element: "Earth",
  },
  {
    id: "five-of-pentacles",
    name: "Five of Pentacles",
    number: 5,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "Financial loss, poverty, lack mindset, isolation, worry, insecurity. Feeling left out in the cold — but help may be closer than you think.",
    reversedMeaning: "Recovery from loss, spiritual poverty, end of hardship. The worst is passing.",
    keywords: ["loss", "poverty", "isolation", "worry", "hardship"],
    symbolism: "Two figures walk past a church in the snow, wounded and poor. Help and warmth are nearby but unseen.",
    love: "Feeling emotionally or materially unsupported. Reach out — help is closer than you think.",
    career: "Financial hardship or feeling excluded at work. This is temporary.",
    personalGrowth: "Material hardship does not define your worth. Seek support without shame.",
    reflectionQuestion: "What support have I been too proud to ask for?",
    element: "Earth",
  },
  {
    id: "six-of-pentacles",
    name: "Six of Pentacles",
    number: 6,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "Giving, receiving, generosity, charity, sharing wealth, fairness. The flow of abundance between those who have and those in need.",
    reversedMeaning: "Self-care needed, strings attached, debts, one-sided generosity. Giving that creates obligation.",
    keywords: ["generosity", "giving", "receiving", "charity", "fairness"],
    symbolism: "A merchant holds balanced scales while giving coins to the poor. Generosity flows in both directions.",
    love: "Generous, balanced exchange. Both giving and receiving in love.",
    career: "Fair compensation for your work. Generosity that uplifts without depleting.",
    personalGrowth: "Give freely and receive gracefully. Both are acts of trust.",
    reflectionQuestion: "How can I balance giving and receiving in my life?",
    element: "Earth",
  },
  {
    id: "seven-of-pentacles",
    name: "Seven of Pentacles",
    number: 7,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "Long-term view, sustainable results, perseverance, investment, patience. Waiting for the harvest after planting the seeds.",
    reversedMeaning: "Lack of long-term vision, limited success, impatience, wasted effort. Not seeing results yet.",
    keywords: ["patience", "investment", "perseverance", "harvest", "long-term view"],
    symbolism: "A figure leans on a hoe, contemplating seven pentacles growing on a lush plant. Patient cultivation before harvest.",
    love: "A relationship that needs time and patience to grow. Invest in what matters.",
    career: "Long-term investments are paying off. Be patient — the harvest is coming.",
    personalGrowth: "Growth takes time. Trust the process and keep nurturing what matters.",
    reflectionQuestion: "What am I patiently cultivating that needs more time?",
    element: "Earth",
  },
  {
    id: "eight-of-pentacles",
    name: "Eight of Pentacles",
    number: 8,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "Apprenticeship, repetitive tasks, mastery, skill development, quality, diligence. The dedication to perfect your craft.",
    reversedMeaning: "Self-development, perfectionism, misdirected activity, lack of focus. Working hard but not working smart.",
    keywords: ["mastery", "diligence", "craftsmanship", "skill", "dedication"],
    symbolism: "A craftsman carefully carves pentacles, each one more refined. Mastery through dedicated practice.",
    love: "Dedication and effort in a relationship. Love grows through consistent care.",
    career: "Skill development and mastery. Dedicate yourself to quality work.",
    personalGrowth: "Excellence comes from practice. Commit to the process.",
    reflectionQuestion: "What skill or craft am I dedicated to mastering?",
    element: "Earth",
  },
  {
    id: "nine-of-pentacles",
    name: "Nine of Pentacles",
    number: 9,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "Abundance, luxury, self-sufficiency, financial independence, refinement. You have built something beautiful through your own effort.",
    reversedMeaning: "Self-worth issues, overinvestment, superficial values, solitude. Material success that feels hollow.",
    keywords: ["abundance", "luxury", "self-sufficiency", "independence", "refinement"],
    symbolism: "A wealthy figure stands in a lush garden with a falcon on their hand. Abundance, refinement, and self-sufficiency.",
    love: "Independence within a relationship. Two whole people choosing each other.",
    career: "Financial independence and success. You have earned this abundance.",
    personalGrowth: "You can enjoy the fruits of your labor. You earned this.",
    reflectionQuestion: "What abundance have I created through my own effort?",
    element: "Earth",
  },
  {
    id: "ten-of-pentacles",
    name: "Ten of Pentacles",
    number: 10,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "Wealth, financial security, family, long-term success, legacy, inheritance. Abundance that extends beyond yourself to future generations.",
    reversedMeaning: "Financial failure, loneliness, family disputes, loss of security. Material success that has crumbled.",
    keywords: ["wealth", "legacy", "family", "security", "inheritance"],
    symbolism: "An elder sits surrounded by family, with pentacles arranged in a tree-like formation. Wealth, legacy, and family continuity.",
    love: "A stable, secure, family-oriented connection. Building something lasting together.",
    career: "Long-term financial success. A legacy being built that will outlast you.",
    personalGrowth: "What legacy are you building? Your actions today shape tomorrow.",
    reflectionQuestion: "What lasting legacy am I building?",
    element: "Earth",
  },
  {
    id: "page-of-pentacles",
    name: "Page of Pentacles",
    number: 11,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "Ambition, desire, diligence, studiousness, new opportunity. A practical beginning with long-term potential.",
    reversedMeaning: "Lack of progress, procrastination, learn from setbacks. Ambition without action.",
    keywords: ["ambition", "diligence", "opportunity", "studiousness", "practicality"],
    symbolism: "A young figure gazes at a pentacle held aloft. Practical ambitions and new financial or educational beginnings.",
    love: "A grounded, practical new connection. Building something real.",
    career: "A new opportunity that requires dedication and learning. Invest in your growth.",
    personalGrowth: "Set practical goals and work toward them steadily.",
    reflectionQuestion: "What practical goal am I ready to work toward?",
    element: "Earth",
  },
  {
    id: "knight-of-pentacles",
    name: "Knight of Pentacles",
    number: 12,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "Hard work, productivity, routine, conservatism, methodical, reliable. Slow and steady wins the race.",
    reversedMeaning: "Self-discipline needed, laziness, obsessiveness, boredom. The grind without the purpose.",
    keywords: ["hard work", "reliability", "methodical", "patience", "diligence"],
    symbolism: "A knight sits patiently on a heavy workhorse, pentacle in hand. Reliable, methodical, and determined.",
    love: "A reliable, steady, dependable partner. Love shown through actions, not words.",
    career: "Steady, methodical progress. Hard work and reliability bring results.",
    personalGrowth: "Consistency is more powerful than intensity. Show up every day.",
    reflectionQuestion: "Where can steady, patient effort bring me results?",
    element: "Earth",
  },
  {
    id: "queen-of-pentacles",
    name: "Queen of Pentacles",
    number: 13,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "Nurturing, practical, providing, down-to-earth, security, abundance. A warm, grounded presence that creates comfort and stability.",
    reversedMeaning: "Financial independence threatened, self-care neglected, smothering. Giving too much, receiving too little.",
    keywords: ["nurturing", "practicality", "abundance", "security", "grounded"],
    symbolism: "A queen sits in a lush garden, cradling a pentacle. Rabbits and flowers surround her. Earthly nurturing and abundance.",
    love: "A nurturing, grounded, generous partner. Creating a warm and stable home.",
    career: "Practical leadership. Creating stability and comfort for yourself and others.",
    personalGrowth: "Nurture yourself and your world. Practical care is a form of love.",
    reflectionQuestion: "How well am I nurturing myself and those I care about?",
    element: "Earth",
  },
  {
    id: "king-of-pentacles",
    name: "King of Pentacles",
    number: 14,
    arcana: "minor",
    suit: "pentacles",
    uprightMeaning: "Wealth, business, leadership, security, discipline, abundance, success. Mastery over the material world through discipline and hard work.",
    reversedMeaning: "Financially inept, obsessed with money, stubborn, poor decisions. Material focus at the expense of the spirit.",
    keywords: ["wealth", "leadership", "success", "discipline", "mastery"],
    symbolism: "A king sits on a throne decorated with bulls and vines, holding a pentacle and scepter. Material mastery and abundance.",
    love: "A stable, generous, successful partner. Security and abundance in love.",
    career: "Financial mastery and business success. Your discipline has paid off.",
    personalGrowth: "True abundance includes inner richness. Do not let material success replace spiritual growth.",
    reflectionQuestion: "How can I use my success to benefit others?",
    element: "Earth",
  },
];

export const ALL_CARDS: TarotCard[] = [
  ...MAJOR_ARCANA,
  ...CUPS,
  ...WANDS,
  ...SWORDS,
  ...PENTACLES,
];
