"use client";

import { motion } from "framer-motion";

export default function TermsPage() {
  return (
    <main className="relative min-h-screen overflow-hidden">
      <div className="global-corners" />
      <div className="relative z-10 pt-24 sm:pt-32 pb-20 px-4 sm:px-6">
        <div className="max-w-2xl mx-auto">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }}>
            <h1 className="text-2xl sm:text-3xl mb-8 text-center" style={{ color: "var(--text-primary)", fontWeight: 300, letterSpacing: "0.02em" }}>
              Terms of Use
            </h1>

            <div className="space-y-8" style={{ color: "var(--text-secondary)", fontSize: "14px", lineHeight: "1.8" }}>
              <section>
                <h2 className="text-lg mb-3" style={{ color: "var(--text-primary)", fontWeight: 400 }}>Acceptance</h2>
                <p>By using Elovayne, you agree to these terms. If you do not agree, please do not use our services.</p>
              </section>

              <section>
                <h2 className="text-lg mb-3" style={{ color: "var(--text-primary)", fontWeight: 400 }}>Our Services</h2>
                <p>Elovayne is a creative community platform offering features like Elyra AI, Tarot readings, creative tools, and community spaces. We reserve the right to modify or discontinue features at any time.</p>
              </section>

              <section>
                <h2 className="text-lg mb-3" style={{ color: "var(--text-primary)", fontWeight: 400 }}>Your Content</h2>
                <p>You retain ownership of content you create on Elovayne. By posting content, you grant us a license to display and distribute it within the Elovayne platform. You are responsible for your content and must not post harmful, illegal, or abusive material.</p>
              </section>

              <section>
                <h2 className="text-lg mb-3" style={{ color: "var(--text-primary)", fontWeight: 400 }}>Elyra AI</h2>
                <p>Elyra is an AI assistant provided for creative and informational purposes. Elyra&apos;s responses are generated by AI and may not always be accurate. Do not rely on Elyra for medical, legal, or financial advice. Elyra should not be used to generate harmful or illegal content.</p>
              </section>

              <section>
                <h2 className="text-lg mb-3" style={{ color: "var(--text-primary)", fontWeight: 400 }}>Tarot</h2>
                <p>Tarot readings on Elovayne are designed for reflection, creativity, and personal exploration. They should not be treated as guaranteed prediction or as professional medical, legal, or financial advice.</p>
              </section>

              <section>
                <h2 className="text-lg mb-3" style={{ color: "var(--text-primary)", fontWeight: 400 }}>Community Guidelines</h2>
                <p>Be kind, respectful, and authentic. Do not harass, bully, or harm others. Do not spam or post misleading content. Respect others&apos; privacy and boundaries.</p>
              </section>

              <section>
                <h2 className="text-lg mb-3" style={{ color: "var(--text-primary)", fontWeight: 400 }}>Limitation of Liability</h2>
                <p>Elovayne is provided &ldquo;as is&rdquo; without warranties. We are not liable for any damages arising from your use of our services. We do not guarantee uninterrupted or error-free service.</p>
              </section>

              <section>
                <h2 className="text-lg mb-3" style={{ color: "var(--text-primary)", fontWeight: 400 }}>Changes</h2>
                <p>We may update these terms from time to time. Continued use of Elovayne after changes constitutes acceptance of the new terms.</p>
              </section>

              <section>
                <h2 className="text-lg mb-3" style={{ color: "var(--text-primary)", fontWeight: 400 }}>Contact</h2>
                <p>For questions about these terms, contact us through our <a href="/support" style={{ color: "#00d4aa", textDecoration: "none", borderBottom: "1px solid rgba(0, 212, 170, 0.3)" }}>Support page</a>.</p>
              </section>

              <p className="text-xs mt-8" style={{ color: "var(--text-dim)" }}>Last updated: January 2026</p>
            </div>
          </motion.div>
        </div>
      </div>
    </main>
  );
}
